#!/usr/bin/env python
# -*- coding: utf-8 -*-

from codegen import *

if __name__ == "__main__":
    func = Function('int', 'main')
    func.addComment()
    func.add(Line('char', 'hello', '=', '\'H\''))
    struct = Struct('PPDLState')
    struct.add(Line('int', 'i'))
    struct.add(Line('char', 'c'))
    struct.add(Line('unsigned long', 'ui'))
    struct.add(Line('char', 'a2'))
    struct.addPrefix('typedef')
    func.add(struct)
    union = Union(Line('g++'))
    _union = Union(Line('k++'))
    union.add(_union)
    cond = If('1', '>' , '0')
    cond.add(Line('int' , 'i'))
    cond.add(union)
    cond.addVar('int', 'k')
    cond.addVar('int', 'g')
    cond.addVar('int', 'l')
    cond.add(Line('' , 'hello', '=', '\'Y\''))
    cond.add(For('i = 0', 'i < 10', 'i++'))
    _for = For('i = 0', 'i < 10', 'i++')
    _for.addComment()
    _for.add(Line('char', 'ItIsFor'))
    cond.addElse(Line('int' , 'i'))
    cond.addElse(_for)
    func.add(cond)
    doWhile = DoWhile('1 > 2')
    _while = While('0 < 1')
    _while.add(Line('char', 'HelloWorld'))
    switch = Switch('HelloWorld')
    switch.add('\'f\'', Line('', 'HelloWorld', '=', '\'g\''))
    switch.add('\'d\'', Line('', 'HelloWorld', '=', '\'\\0\''))
    switch.addDefault(Line('', 'HelloWorld', '=', '\'\\0\''))
    _while.add(switch)
    doWhile.add(_while)
    func.add(doWhile)
    source = Source()
    source.add(Pragma("warning(disable:4047)"))
    ifdef = Ifdef("unix")
    ifdef.add(Define("DEBUG_NIX", "1"))
    ifdef.addElse(Include("\"stdio.h\""))
    source.add(ifdef)
    ifndef = Ifdef("unix", negative = True)
    ifndef.add(Define("DEBUG_WIN", "1"))
    source.add(ifndef)
    source.add(struct)
    source.add(func)
    print source
